In [1]:
import pandas as pd
import numpy as np

In [2]:
player_2017_2018 = pd.read_pickle('player_2017_2018_w_hand_calc_DKPTS.pkl')
team_2017_2018 = pd.read_pickle('team_2017_18_w_opponent_stats.pkl')
player_2017_2018.columns
team_2017_2018.columns

Index(['DATASET', 'DATE', 'TEAMS', 'VENUE', '1Q', '2Q', '3Q', '4Q', 'OT1',
       'OT2', 'OT3', 'OT4', 'F', 'MIN', 'FG', 'FGA', '3P', '3PA', 'FT', 'FTA',
       'OR', 'DR', 'TOT', 'A', 'PF', 'ST', 'TO', 'TO TO', 'BL', 'PTS', 'POSS',
       'PACE', 'OEFF', 'DEFF', 'REST DAYS', 'STARTING LINEUPS', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'MAIN REF', 'CREW',
       'OPENING ODDS', 'OPENING SPREAD', 'OPENING TOTAL', 'MOVEMENTS',
       'CLOSING ODDS', 'MONEYLINE', 'HALFTIME', 'BOX SCORE', 'ODDS',
       'pace_roll2', 'pace_roll3', 'pace_roll5', 'pace_roll10', 'oeff_roll2',
       'oeff_roll3', 'oeff_roll5', 'oeff_roll10', 'deff_roll2', 'deff_roll3',
       'deff_roll5', 'deff_roll10', 'opp_TEAMS', 'opp_pace_roll2',
       'opp_pace_roll3', 'opp_pace_roll5', 'opp_pace_roll10', 'opp_oeff_roll2',
       'opp_oeff_roll3', 'opp_oeff_roll5', 'opp_oeff_roll10', 'opp_deff_roll2',
       'opp_deff_roll3', 'opp_deff_roll5', 'opp_deff_roll10'],
      dtype='object')

In [3]:
player_2017_2018.head()

,DATASET,DATE,PLAYER,POSITION,TEAM,OPPONENT,ROAD_HOME,MINUTES,FG,FGA,...,DR,TOT,A,PF,ST,TO,BL,PTS,DT_Double,DraftKings_PTS
0,2017-2018 Regular Season,10/17/2017,Gordon Hayward,SF,Boston,Cleveland,R,5.25,1,2,...,1,1,0,1,0,0,0,2,0.0,3.25
1,2017-2018 Regular Season,10/17/2017,Jayson Tatum,SF,Boston,Cleveland,R,36.53,5,12,...,6,10,3,4,0,1,0,14,1.0,32.50
2,2017-2018 Regular Season,10/17/2017,Al Horford,C,Boston,Cleveland,R,32.12,2,7,...,7,7,5,2,0,0,1,9,0.0,27.25
3,2017-2018 Regular Season,10/17/2017,Jaylen Brown,SF,Boston,Cleveland,R,39.60,11,23,...,5,6,0,5,2,3,0,25,0.0,36.00
4,2017-2018 Regular Season,10/17/2017,Kyrie Irving,PG,Boston,Cleveland,R,39.35,8,17,...,2,4,10,4,3,2,0,22,1.0,50.50

In [4]:
df = player_2017_2018[['DATE','TEAM','POSITION','DraftKings_PTS']]

In [5]:
df.head()

         DATE    TEAM POSITION  DraftKings_PTS
0  10/17/2017  Boston       SF            3.25
1  10/17/2017  Boston       SF           32.50
2  10/17/2017  Boston        C           27.25
3  10/17/2017  Boston       SF           36.00
4  10/17/2017  Boston       PG           50.50

In [6]:
df.POSITION.unique()

array(['SF', 'C', 'PG', 'PF', 'SG', 'F', 'G'], dtype=object)

In [7]:
positional_pts = df.groupby(['DATE','TEAM','POSITION']).sum()

In [8]:
positional_pts = positional_pts.unstack(level=-1)

In [9]:
positional_pts.head()

                     DraftKings_PTS
POSITION                          C   F    G      PF     PG     SF     SG
DATE       TEAM
01/01/2018 Brooklyn           45.75 NaN  NaN    1.50  24.75  59.75  90.25
           Chicago            35.50 NaN  NaN  102.75  54.00   3.25  64.00
           LA Lakers          13.25 NaN  5.5   59.25  24.50  40.75  51.50
           Milwaukee          23.25 NaN  NaN  105.50  78.00   6.00  32.00
           Minnesota          41.50 NaN  NaN   59.25  22.25  95.00  20.75

In [10]:
positional_pts = positional_pts.xs('DraftKings_PTS', axis=1, drop_level=True)

In [11]:
positional_pts = positional_pts.reset_index(level=1)

In [12]:
positional_pts = positional_pts.reset_index()

In [13]:
positional_pts = positional_pts.rename(columns={'TEAM':'TEAMS','C':'C_DK_PTS','F':'F_DK_PTS','G':'G_DK_PTS','PF':'PF_DK_PTS','PG':'PG_DK_PTS','SF':'SF_DK_PTS','SG':'SG_DK_PTS'})

In [14]:
positional_pts = positional_pts.set_index(['DATE','TEAMS'])

In [15]:
positional_pts.head()

POSITION              C_DK_PTS  F_DK_PTS  G_DK_PTS  PF_DK_PTS  PG_DK_PTS  \
DATE       TEAMS
01/01/2018 Brooklyn      45.75       NaN       NaN       1.50      24.75
           Chicago       35.50       NaN       NaN     102.75      54.00
           LA Lakers     13.25       NaN       5.5      59.25      24.50
           Milwaukee     23.25       NaN       NaN     105.50      78.00
           Minnesota     41.50       NaN       NaN      59.25      22.25

POSITION              SF_DK_PTS  SG_DK_PTS
DATE       TEAMS
01/01/2018 Brooklyn       59.75      90.25
           Chicago         3.25      64.00
           LA Lakers      40.75      51.50
           Milwaukee       6.00      32.00
           Minnesota      95.00      20.75

In [16]:
result = team_2017_2018.join(positional_pts,on=['DATE','TEAMS'])

In [17]:
result.head(30)

,DATASET,DATE,TEAMS,VENUE,1Q,2Q,3Q,4Q,OT1,OT2,...,opp_deff_roll3,opp_deff_roll5,opp_deff_roll10,C_DK_PTS,F_DK_PTS,G_DK_PTS,PF_DK_PTS,PG_DK_PTS,SF_DK_PTS,SG_DK_PTS
0,2017-2018 Regular Season,10/17/2017,Boston,Road,19,19,33,28,NaN,NaN,...,NaN,NaN,NaN,42.00,NaN,NaN,0.00,110.75,71.75,NaN
1,2017-2018 Regular Season,10/17/2017,Cleveland,Home,29,25,18,30,NaN,NaN,...,NaN,NaN,NaN,14.50,NaN,NaN,29.75,21.50,96.25,42.00
2,2017-2018 Regular Season,10/17/2017,Houston,Road,34,28,26,34,NaN,NaN,...,NaN,NaN,NaN,20.00,NaN,NaN,49.00,89.50,58.50,31.75
3,2017-2018 Regular Season,10/17/2017,Golden State,Home,35,36,30,20,NaN,NaN,...,NaN,NaN,NaN,11.75,NaN,NaN,65.75,51.00,45.00,78.75
4,2017-2018 Regular Season,10/18/2017,Charlotte,Road,27,18,25,20,NaN,NaN,...,NaN,NaN,NaN,48.25,NaN,NaN,30.75,51.75,NaN,53.50
5,2017-2018 Regular Season,10/18/2017,Detroit,Home,29,27,26,20,NaN,NaN,...,NaN,NaN,NaN,36.25,NaN,NaN,86.00,76.00,16.50,18.00
6,2017-2018 Regular Season,10/18/2017,Brooklyn,Road,30,33,35,33,NaN,NaN,...,NaN,NaN,NaN,6.75,NaN,NaN,44.50,78.00,49.25,54.75
7,2017-2018 Regular Season,10/18/2017,Indiana,Home,29,36,41,34,NaN,NaN,...,NaN,NaN,NaN,51.00,NaN,NaN,76.00,46.25,13.00,100.00
8,2017-2018 Regular Season,10/18/2017,Miami,Road,37,18,23,31,NaN,NaN,...,NaN,NaN,NaN,79.75,NaN,NaN,30.00,34.75,20.00,59.00
9,2017-2018 Regular Season,10/18/2017,Orlando,Home,32,26,30,28,NaN,NaN,...,NaN,NaN,NaN,62.25,NaN,NaN,NaN,50.75,85.25,45.75
10,2017-2018 Regular Season,10/18/2017,Philadelphia,Road,23,36,23,33,NaN,NaN,...,NaN,NaN,NaN,40.25,NaN,NaN,24.00,91.50,59.25,23.50
11,2017-2018 Regular Season,10/18/2017,Washington,Home,32,24,34,30,NaN,NaN,...,NaN,NaN,NaN,61.00,NaN,NaN,9.50,55.75,64.50,61.75
12,2017-2018 Regular Season,10/18/2017,Milwaukee,Road,24,34,18,32,NaN,NaN,...,101.713094,101.713094,101.713094,42.00,NaN,NaN,111.25,18.25,12.00,26.75
13,2017-2018 Regular Season,10/18/2017,Boston,Home,26,27,27,20,NaN,NaN,...,NaN,NaN,NaN,42.00,NaN,NaN,12.25,103.00,58.50,NaN
14,2017-2018 Regular Season,10/18/2017,New Orleans,Road,34,18,18,21,NaN,NaN,...,NaN,NaN,NaN,58.50,NaN,NaN,57.00,18.50,24.75,48.50
15,2017-2018 Regular Season,10/18/2017,Memphis,Home,27,27,25,24,NaN,NaN,...,NaN,NaN,NaN,41.25,NaN,NaN,34.00,56.75,82.75,7.50
16,2017-2018 Regular Season,10/18/2017,Atlanta,Road,27,31,24,35,NaN,NaN,...,NaN,NaN,NaN,35.25,NaN,NaN,42.75,57.00,72.25,35.75
17,2017-2018 Regular Season,10/18/2017,Dallas,Home,24,23,35,29,NaN,NaN,...,NaN,NaN,NaN,10.50,NaN,NaN,62.50,89.00,28.25,34.50
18,2017-2018 Regular Season,10/18/2017,Denver,Road,30,28,25,13,NaN,NaN,...,NaN,NaN,NaN,13.00,NaN,NaN,59.75,13.25,19.00,80.50
19,2017-2018 Regular Season,10/18/2017,Utah,Home,21,28,29,28,NaN,NaN,...,NaN,NaN,NaN,32.50,NaN,NaN,36.50,33.25,69.75,47.50
20,2017-2018 Regular Season,10/18/2017,Minnesota,Road,25,24,28,22,NaN,NaN,...,NaN,NaN,NaN,42.25,NaN,NaN,42.25,35.50,64.75,22.25
21,2017-2018 Regular Season,10/18/2017,San Antonio,Home,32,21,34,20,NaN,NaN,...,NaN,NaN,NaN,36.50,NaN,NaN,50.50,44.75,25.25,83.50
22,2017-2018 Regular Season,10/18/2017,Portland,Road,29,31,38,26,NaN,NaN,...,NaN,NaN,NaN,27.25,NaN,NaN,49.75,73.50,52.25,56.00
23,2017-2018 Regular Season,10/18/2017,Phoenix,Home,21,14,20,21,NaN,NaN,...,NaN,NaN,NaN,10.75,NaN,NaN,27.25,52.00,34.75,37.00
24,2017-2018 Regular Season,10/18/2017,Houston,Road,26,26,23,30,NaN,NaN,...,NaN,NaN,NaN,70.25,NaN,NaN,25.75,59.00,19.00,35.00
25,2017-2018 Regular Season,10/18/2017,Sacramento,Home,25,23,24,28,NaN,NaN,...,118.037068,118.037068,118.037068,53.00,NaN,NaN,25.00,47.75,8.00,63.75
26,2017-2018 Regular Season,10/19/2017,Chicago,Road,23,14,27,36,NaN,NaN,...,NaN,NaN,NaN,37.50,NaN,NaN,28.50,50.50,18.25,60.50
27,2017-2018 Regular Season,10/19/2017,Toronto,Home,25,33,26,33,NaN,NaN,...,NaN,NaN,NaN,58.50,0.0,NaN,20.00,65.25,47.50,53.50
28,2017-2018 Regular Season,10/19/2017,New York,Road,24,18,17,25,NaN,NaN,...,NaN,NaN,NaN,28.25,NaN,NaN,77.75,11.00,17.25,46.00
29,2017-2018 Regular Season,10/19/2017,Oklahoma City,Home,27,26,26,26,NaN,NaN,...,NaN,NaN,NaN,46.25,NaN,NaN,2.00,73.00,107.25,9.75

In [18]:
result.to_pickle('team_2017_18_w_opponent_stats_and_DvP.pkl')